import { randomUUID } from 'node:crypto'
import { ZodError } from 'zod'
import type { Locale } from '@klyrow/contracts'
import { createConsentPreferences, parseConsentPreferences } from '../../../legal/consent'
import { ApiProblem, validationProblem } from '../../errors/api-problem'
import { createRequestContext, createRequestId } from '../../observability/request-context'
import { apiOperations } from '../../registry/api-operations'
import { cookiePreferencesSchema, publicSubmissionSchema, toolInputSchema } from '../../schemas/public-submission'
import { middlewareReadiness } from '../../config/middleware-config'
import { getPublicFeatures, getPublicLegalDocument, getPublicLegalDocuments, getPublicNavigation, getPublicPricing } from '../../services/public-catalog-service'
import { getSubmissionService } from '../../services/submission-service'
import { apiSandboxFixture, createMigrationPlan, inspectDomainReadiness, pricingEstimate, searchPublicContent } from '../../services/tool-service'

const submissionRoutes: Record<string, { operationId: string; eventType: string }> = {
  '/api/v1/leads/demo': { operationId: 'requestDemo', eventType: 'klyrow.website.demo.requested.v1' }, '/api/v1/leads/sales': { operationId: 'contactSales', eventType: 'klyrow.website.sales.requested.v1' }, '/api/v1/leads/pricing': { operationId: 'requestPricing', eventType: 'klyrow.website.pricing.requested.v1' }, '/api/v1/leads/developer-interest': { operationId: 'developerInterest', eventType: 'klyrow.website.developer_interest.created.v1' }, '/api/v1/leads/partner-application': { operationId: 'partnerApplication', eventType: 'klyrow.website.partner_application.created.v1' }, '/api/v1/leads/migration-consultation': { operationId: 'migrationConsultation', eventType: 'klyrow.website.migration_consultation.requested.v1' }, '/api/v1/leads/dpa-request': { operationId: 'dpaRequest', eventType: 'klyrow.website.dpa_request.created.v1' }, '/api/v1/leads/security-consultation': { operationId: 'securityConsultation', eventType: 'klyrow.website.security_consultation.created.v1' }, '/api/v1/support/contact': { operationId: 'supportContact', eventType: 'klyrow.website.support_contact.created.v1' }, '/api/v1/abuse/report': { operationId: 'abuseReport', eventType: 'klyrow.website.abuse_report.created.v1' }, '/api/v1/security/report': { operationId: 'securityReport', eventType: 'klyrow.website.security_report.created.v1' }, '/api/v1/subscriptions/newsletter': { operationId: 'newsletterSubscription', eventType: 'klyrow.website.newsletter_subscription.requested.v1' }, '/api/v1/subscriptions/subprocessor-updates': { operationId: 'subprocessorUpdates', eventType: 'klyrow.website.subprocessor_updates.requested.v1' }, '/api/v1/subscriptions/legal-updates': { operationId: 'legalUpdates', eventType: 'klyrow.website.legal_updates.requested.v1' }, '/api/v1/privacy/requests': { operationId: 'privacyRequest', eventType: 'klyrow.website.privacy_request.created.v1' }, '/api/v1/privacy/opt-out': { operationId: 'privacyOptOut', eventType: 'klyrow.website.privacy_opt_out.created.v1' },
}
const windows = new Map<string, { count: number; resetAt: number }>()
const checkRate = (key: string, limit = 12) => { const now = Date.now(); const current = windows.get(key); if (!current || current.resetAt <= now) { windows.set(key, { count: 1, resetAt: now + 60000 }); return } current.count += 1; if (current.count > limit) throw new ApiProblem(429, 'RATE_LIMITED', 'Too many requests. Try again shortly.') }
const success = <T>(requestId: string, data: T, status = 'ok') => ({ request_id: requestId, status, received_at: new Date().toISOString(), data })
const parseLocale = (value: unknown): Locale => (value === 'es' ? 'es' : 'en')
const cookieDefaults = () => createConsentPreferences({}, 'api')

export default defineEventHandler(async (event) => {
  const requestId = createRequestId(getHeader(event, 'x-request-id')); setHeader(event, 'x-request-id', requestId); setHeader(event, 'cache-control', 'no-store')
  const method = getMethod(event).toUpperCase(); const path = getRequestURL(event).pathname.replace(/\/$/, '') || '/'; const config = useRuntimeConfig(event); const locale = parseLocale(getQuery(event).locale)
  try {
    checkRate(`${getRequestIP(event, { xForwardedFor: true }) ?? 'unknown'}:${method}:${path}`, path.includes('/tools/') ? 8 : 12)
    if (method === 'GET' && path === '/api/v1/health') return success(requestId, { status: 'healthy', release_sha: String(config.public.releaseSha) })
    if (method === 'GET' && path === '/api/v1/ready') return success(requestId, { status: 'ready', dependencies: { middleware: middlewareReadiness(config) } })
    if (method === 'GET' && path === '/api/v1/public/config') { const csrfToken = `csrf_${randomUUID().replaceAll('-', '')}`; setCookie(event, 'klyrow_csrf', csrfToken, { httpOnly: false, sameSite: 'strict', secure: process.env.NODE_ENV === 'production', path: '/', maxAge: 3600 }); return success(requestId, { locales: ['en', 'es'], sign_in_url: String(config.public.signInUrl || ''), docs_url: String(config.public.docsUrl || ''), status_url: String(config.public.statusUrl || ''), scheduling_url: String(config.public.schedulingUrl || ''), pricing_mode: String(config.public.pricingMode || 'contact_sales'), csrf_token: csrfToken }) }
    if (method === 'GET' && path === '/api/v1/public/navigation') return success(requestId, getPublicNavigation(locale)); if (method === 'GET' && path === '/api/v1/public/features') return success(requestId, getPublicFeatures(locale)); if (method === 'GET' && path === '/api/v1/public/pricing') return success(requestId, getPublicPricing(locale, String(config.public.pricingMode || 'contact_sales'))); if (method === 'GET' && path === '/api/v1/public/legal-documents') return success(requestId, getPublicLegalDocuments(locale))
    if (method === 'GET' && /^\/api\/v1\/public\/legal-documents\/[^/]+$/.test(path)) { const document = getPublicLegalDocument(locale, decodeURIComponent(path.split('/').at(-1) ?? '')); if (!document) throw new ApiProblem(404, 'LEGAL_DOCUMENT_NOT_FOUND', 'The legal document is not published.'); return success(requestId, document) }
    if (method === 'GET' && path === '/api/v1/consent/cookies/config') return success(requestId, { version: 'cookie-policy-v1', categories: ['necessary', 'preferences', 'analytics', 'marketing'], strict_mode: true }); if (method === 'GET' && path === '/api/v1/consent/cookies/current') return success(requestId, parseConsentPreferences(getCookie(event, 'klyrow_consent')) ?? cookieDefaults()); if (method === 'GET' && /^\/api\/v1\/privacy\/requests\/[^/]+$/.test(path)) return success(requestId, { status: 'received', public_reference: path.split('/').at(-1)?.slice(0, 12) }); if (method === 'GET' && path === '/api/v1/tools/content-search') return success(requestId, searchPublicContent(String(getQuery(event).q ?? ''), locale)); if (method === 'GET' && path === '/api/v1/openapi') return success(requestId, { openapi: '3.1.0', info: { title: 'Klyrow Website BFF', version: String(config.public.releaseSha) }, operations: apiOperations })
    if (!['POST', 'PUT'].includes(method)) throw new ApiProblem(404, 'NOT_FOUND', 'No API operation matches this request.')
    const origin = getHeader(event, 'origin'); if (origin) { const allowedOrigin = new URL(String(config.public.publicBaseUrl)).origin; if (origin !== allowedOrigin) throw new ApiProblem(403, 'ORIGIN_DENIED', 'The request origin is not allowed.'); const csrfHeader = getHeader(event, 'x-csrf-token'); if (!csrfHeader || csrfHeader !== getCookie(event, 'klyrow_csrf')) throw new ApiProblem(403, 'CSRF_DENIED', 'The CSRF token is missing or invalid.') }
    const idempotencyKey = getHeader(event, 'idempotency-key'); if (!idempotencyKey || idempotencyKey.length < 12 || idempotencyKey.length > 200) throw new ApiProblem(400, 'IDEMPOTENCY_REQUIRED', 'A valid Idempotency-Key header is required.')
    const raw = (await readRawBody(event, 'utf8')) ?? '{}'; if (Buffer.byteLength(raw, 'utf8') > 65536) throw new ApiProblem(413, 'BODY_TOO_LARGE', 'The request body is too large.'); let rawBody: Record<string, unknown>; try { const parsed: unknown = JSON.parse(raw); if (!parsed || typeof parsed !== 'object' || Array.isArray(parsed)) throw new Error('object required'); rawBody = parsed as Record<string, unknown> } catch { throw new ApiProblem(400, 'MALFORMED_REQUEST', 'The request body must be valid JSON.') }
    if (method === 'PUT' && path === '/api/v1/consent/cookies') { const parsed = cookiePreferencesSchema.parse(rawBody); const next = createConsentPreferences(parsed, 'api'); setCookie(event, 'klyrow_consent', JSON.stringify(next), { httpOnly: false, sameSite: 'lax', secure: process.env.NODE_ENV === 'production', path: '/', maxAge: 31536000 }); return success(requestId, next, 'updated') }
    if (method === 'POST' && path === '/api/v1/consent/cookies/reset') { deleteCookie(event, 'klyrow_consent', { path: '/' }); return success(requestId, cookieDefaults(), 'reset') }
    const toolBody = toolInputSchema.parse(rawBody); if (method === 'POST' && path === '/api/v1/tools/pricing-estimate') return success(requestId, pricingEstimate(toolBody, String(config.public.pricingMode || 'contact_sales'), String(config.pricingConfigJson || ''))); if (method === 'POST' && path === '/api/v1/tools/domain-readiness') return success(requestId, await inspectDomainReadiness(toolBody)); if (method === 'POST' && path === '/api/v1/tools/api-sandbox') return success(requestId, apiSandboxFixture(toolBody)); if (method === 'POST' && path === '/api/v1/tools/migration-plan') return success(requestId, createMigrationPlan(toolBody))
    const submissionRoute = submissionRoutes[path]; if (!submissionRoute) throw new ApiProblem(404, 'NOT_FOUND', 'No API operation matches this request.'); const body = publicSubmissionSchema.parse(rawBody); if (body.anti_abuse.honeypot) throw new ApiProblem(422, 'SPAM_REJECTED', 'The request could not be accepted.'); if (Date.now() - Date.parse(body.anti_abuse.started_at) < 1200) throw new ApiProblem(422, 'SUBMISSION_TOO_FAST', 'Please review the form before submitting.'); if (!body.consent.service_contact) throw new ApiProblem(422, 'CONSENT_REQUIRED', 'Service-contact consent is required for this request.')
    const context = createRequestContext({ requestId, locale: body.locale, routeId: submissionRoute.operationId, origin, ip: getRequestIP(event, { xForwardedFor: true }), userAgent: getHeader(event, 'user-agent') }); const result = await getSubmissionService(config).submit({ context, operationId: submissionRoute.operationId, eventType: submissionRoute.eventType, idempotencyKey, body, locale: body.locale }); setResponseStatus(event, 202); return { request_id: requestId, ...result }
  } catch (error: unknown) { const problem = error instanceof ZodError ? validationProblem(error.issues.map((issue) => ({ field: issue.path.join('.') || 'body', code: issue.code.toUpperCase() }))) : error instanceof ApiProblem ? error : new ApiProblem(500, 'INTERNAL_ERROR', 'The request could not be completed.'); setResponseStatus(event, problem.status); setHeader(event, 'content-type', 'application/problem+json'); return { type: problem.type, title: problem.code.replaceAll('_', ' '), status: problem.status, code: problem.code, detail: problem.message, request_id: requestId, ...(problem.fields ? { errors: problem.fields } : {}) } }
})
